export const BOARD_BG_COLORS = [
  'rgb(78, 36, 100)',
  'rgb(100, 57, 36)',
  'rgb(125, 28, 126)',
  'rgb(195, 89, 89)',
];

export const DEFAULT_PUZZLE = `あ-->a [a] hiragana
い-->i [i] hiragana
う-->u [ɯ] hiragana
え-->e [e] hiragana
お-->o [o] hiragana
か-->ka [ka] hiragana
き-->ki [ki] hiragana
く-->ku [kɯ] hiragana
け-->ke [ke] hiragana
こ-->ko [ko] hiragana
きゃ-->kya [kʲa] hiragana
きゅ-->kyu [kʲɯ] hiragana
きょ-->kyo [kʲo] hiragana
さ-->sa [sa] hiragana
し-->shi [ɕi] hiragana
す-->su [sɯ] hiragana
せ-->se [se] hiragana
そ-->so [so] hiragana
しゃ-->sha [ɕa] hiragana
しゅ-->shu [ɕɯ] hiragana
しょ-->sho [ɕo] hiragana
た-->ta [ta] hiragana
ち-->chi [tɕi] hiragana
つ-->tsu [tsɯ] hiragana
て-->te [te] hiragana
と-->to [to] hiragana
ちゃ-->cha [tɕa] hiragana
ちゅ-->chu [tɕɯ] hiragana
ちょ-->cho [tɕo] hiragana
な-->na [na] hiragana
に-->ni [ɲi] hiragana
ぬ-->nu [nɯ] hiragana
ね-->ne [ne] hiragana
の-->no [no] hiragana
にゃ-->nya [ɲa] hiragana
にゅ-->nyu [ɲɯ] hiragana
にょ-->nyo [ɲo] hiragana
は-->ha [ha] hiragana
ひ-->hi [çi] hiragana
ふ-->fu [ɸɯ] hiragana
へ-->he [he] hiragana
ほ-->ho [ho] hiragana
ひゃ-->hya [ça] hiragana
ひゅ-->hyu [çɯ] hiragana
ひょ-->hyo [ço] hiragana
ま-->ma [ma] hiragana
み-->mi [mi] hiragana
む-->mu [mɯ] hiragana
め-->me [me] hiragana
も-->mo [mo] hiragana
みゃ-->mya [mʲa] hiragana
みゅ-->myu [mʲɯ] hiragana
みょ-->myo [mʲo] hiragana
や-->ya [ja] hiragana
ゆ-->yu [jɯ] hiragana
よ-->yo [jo] hiragana
ら-->ra [ɾa] hiragana
り-->ri [ɾi] hiragana
る-->ru [ɾɯ] hiragana
れ-->re [ɾe] hiragana
ろ-->ro [ɾo] hiragana
りゃ-->rya [ɾʲa] hiragana
りゅ-->ryu [ɾʲɯ] hiragana
りょ-->ryo [ɾʲo] hiragana
わ-->wa [wa] hiragana
ゐ-->wi [i] hiragana
ゑ-->we [e] hiragana
を-->wo [o] hiragana
が-->ga [ɡa] hiragana
ぎ-->gi [ɡi] hiragana
ぐ-->gu [ɡɯ] hiragana
げ-->ge [ɡe] hiragana
ご-->go [ɡo] hiragana
ぎゃ-->gya [ɡʲa] hiragana
ぎゅ-->gyu [ɡʲɯ] hiragana
ぎょ-->gyo [ɡʲo] hiragana
ざ-->za [(d)za] hiragana
じ-->ji [(d)ʑi] hiragana
ず-->zu [(d)zɯ] hiragana
ぜ-->ze [(d)ze] hiragana
ぞ-->zo [(d)zo] hiragana
じゃ-->ja [(d)ʑa] hiragana
じゅ-->ju [(d)ʑɯ] hiragana
じょ-->jo [(d)ʑo] hiragana
だ-->da [da] hiragana
ぢ-->ji (dji) [(d)ʑi] hiragana
づ-->zu (dzu) [(d)zɯ] hiragana
で-->de [de] hiragana
ど-->do [do] hiragana
ぢゃ-->ja (dja) [(d)ʑa] hiragana
ぢゅ-->ju (dju) [(d)ʑɯ] hiragana
ぢょ-->jo (djo) [(d)ʑo] hiragana
ば-->ba [ba] hiragana
び-->bi [bi] hiragana
ぶ-->bu [bɯ] hiragana
べ-->be [be] hiragana
ぼ-->bo [bo] hiragana
びゃ-->bya [bʲa] hiragana
びゅ-->byu [bʲɯ] hiragana
びょ-->byo [bʲo] hiragana
ぱ-->pa [pa] hiragana
ぴ-->pi [pi] hiragana
ぷ-->pu [pɯ] hiragana
ぺ-->pe [pe] hiragana
ぽ-->po [po] hiragana
ぴゃ-->pya [pʲa] hiragana
ぴゅ-->pyu [pʲɯ] hiragana
ぴょ-->pyo [pʲo] hiragana`;

